# -*- coding: utf-8 -*-
"""Face Mask Detection using CNN.ipynb

Automatically generated by Colab.


"""

!pip install kaggle -q
 
"""## 1. Kaggle API setup
Upload your `kaggle.json` when prompted (Kaggle account → Settings → API → Create New Token).
**Important:** since your previous key was shared in a chat, go to Kaggle → Account → API → "Expire Token" and generate a fresh one before using it here."""
 
from google.colab import files
uploaded = files.upload()  # select your kaggle.json here
 
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
 
!kaggle datasets download -d omkargurav/face-mask-dataset
 
from zipfile import ZipFile
 
dataset = '/content/face-mask-dataset.zip'
with ZipFile(dataset, 'r') as zip_ref:
    zip_ref.extractall()
print('The dataset is extracted')
 
import os
 
with_mask_dir = '/content/data/with_mask'
without_mask_dir = '/content/data/without_mask'
 
filenames_with_mask = os.listdir(with_mask_dir)
filenames_without_mask = os.listdir(without_mask_dir)
 
num_of_with_mask = len(filenames_with_mask)
num_of_without_mask = len(filenames_without_mask)
 
print('Number of images with mask:', num_of_with_mask)
print('Number of images without mask:', num_of_without_mask)
 
import numpy as np
import cv2
import glob
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
 
"""## 2. Labels
`1` --> with mask, `0` --> without mask"""
 
with_mask_labels = [1] * num_of_with_mask
without_mask_labels = [0] * num_of_without_mask
 
labels = with_mask_labels + without_mask_labels
print('Total labels:', len(labels))
 
"""## 3. Quick look at a few sample images"""
 
img = mpimg.imread(os.path.join(with_mask_dir, filenames_with_mask[0]))
plt.imshow(img)
plt.title('With mask (sample)')
plt.show()
 
img = mpimg.imread(os.path.join(without_mask_dir, filenames_without_mask[0]))
plt.imshow(img)
plt.title('Without mask (sample)')
plt.show()
 
"""## 4. Resize all images to a fixed size (128x128) and convert to RGB"""
 
IMG_SIZE = 128
 
os.makedirs('with_mask_resized', exist_ok=True)
os.makedirs('without_mask_resized', exist_ok=True)
 
with_mask_resized_folder = '/content/with_mask_resized/'
without_mask_resized_folder = '/content/without_mask_resized/'
 
def resize_and_save(src_folder, dst_folder):
    for filename in os.listdir(src_folder):
        img_path = os.path.join(src_folder, filename)
        try:
            img = Image.open(img_path).convert('RGB').resize((IMG_SIZE, IMG_SIZE))
            img.save(os.path.join(dst_folder, filename))
        except Exception as e:
            print(f'Skipping {filename}: {e}')
 
resize_and_save(with_mask_dir, with_mask_resized_folder)
resize_and_save(without_mask_dir, without_mask_resized_folder)
 
print('Resizing done')
 
"""## 5. Load resized images into numpy arrays"""
 
def load_images(folder):
    files_list = []
    for ext in ('*.png', '*.jpg', '*.jpeg'):
        files_list.extend(glob.glob(os.path.join(folder, ext)))
    images = []
    for f in files_list:
        img = cv2.imread(f)
        if img is not None:
            images.append(img)
    return np.asarray(images)
 
with_mask_images = load_images(with_mask_resized_folder)
without_mask_images = load_images(without_mask_resized_folder)
 
print(with_mask_images.shape, without_mask_images.shape)
 
X = np.concatenate((with_mask_images, without_mask_images))
Y = np.asarray(labels[:len(X)])  # safety: match length in case a few images failed to load
 
print('X shape:', X.shape)
print('Y shape:', Y.shape)
 
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=2, stratify=Y
)
 
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)
 
X_train_std = X_train.astype('float32') / 255.0
X_test_std = X_test.astype('float32') / 255.0
 
"""## 6. Build the CNN model
 
This is the actual CNN — Conv2D + MaxPooling layers extract spatial features
before the Dense layers classify them. This replaces the earlier plain
Flatten+Dense (ANN) approach."""
 
model = keras.Sequential([
    keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    keras.layers.MaxPooling2D((2, 2)),
 
    keras.layers.Conv2D(64, (3, 3), activation='relu'),
    keras.layers.MaxPooling2D((2, 2)),
 
    keras.layers.Conv2D(128, (3, 3), activation='relu'),
    keras.layers.MaxPooling2D((2, 2)),
 
    keras.layers.Flatten(),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(1, activation='sigmoid')  # single output: probability of "with mask"
])
 
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
 
model.summary()
 
history = model.fit(
    X_train_std, Y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32
)
 
score, acc = model.evaluate(X_test_std, Y_test)
print('Test data loss:', score)
print('Test data accuracy:', acc)
 
"""## 7. Training curves (optional but useful to check overfitting)"""
 
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()
 
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()
 
"""## 8. Prediction on a new image (bug fixed)
 
The original code used `np.argmax()` on a single sigmoid output, which
always returns `0`, and then manually overrode the result so it always
printed "wearing mask" regardless of the actual image. Since the model
now outputs a single probability, we just threshold it at 0.5."""
 
def predict_mask(image_path, model, img_size=IMG_SIZE, threshold=0.5):
    input_image = cv2.imread(image_path)
    if input_image is None:
        raise ValueError(f'Could not read image at {image_path}')
 
    resized = cv2.resize(input_image, (img_size, img_size))
    normalized = resized.astype('float32') / 255.0
    batch = np.expand_dims(normalized, axis=0)  # shape (1, 128, 128, 3)
 
    prob_with_mask = model.predict(batch)[0][0]
    label = 1 if prob_with_mask >= threshold else 0
 
    print(f'Predicted probability of wearing a mask: {prob_with_mask:.4f}')
    if label == 1:
        print('The person is wearing a mask')
    else:
        print('The person is NOT wearing a mask')
 
    return label, prob_with_mask
 
input_image_path = input('Path of the image to be predicted: ')
predict_mask(input_image_path, model)
 