# -*- coding: utf-8 -*-
"""Face Mask Detection using CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDhwylbTDigI7DORa-yYEfssihgF__4Z
"""

!pip install kaggle

# configuring the path of Kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d omkargurav/face-mask-dataset

from zipfile import ZipFile
dataset = '/content/face-mask-dataset.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print(' The dataset is extracted')

!ls

import os

filenames_with_mask = os.listdir('/content/data/with_mask')
print(filenames_with_mask)

filenames_without_mask = os.listdir('/content/data/without_mask')
print(filenames_without_mask)

num_of_with_mask = len(filenames_with_mask)
print('Number of images with mask:', num_of_with_mask)

num_of_without_mask = len(filenames_without_mask)
print('Number of images without mask:', num_of_without_mask)

import numpy as np
from PIL import Image
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

with_mask_labels = [1]*3725
print(with_mask_labels)

without_mask_labels = [0]*3828
print(without_mask_labels)

labels = with_mask_labels + without_mask_labels
print(len(labels))

print(labels)

"""1 --> with mask
0 --> without mask
"""

img = mpimg.imread('/content/data/with_mask/with_mask_10.jpg')
plt.imshow(img)

img = mpimg.imread('/content/data/with_mask/with_mask_100.jpg')
plt.imshow(img)

img = mpimg.imread('/content/data/without_mask/without_mask_10.jpg')
plt.imshow(img)

os.mkdir('with_mask_resized')
os.mkdir('without_mask_resized')

with_mask_folder = '/content/data/with_mask/'
with_mask_resized_folder = '/content/with_mask_resized/'
for filename in os.listdir(with_mask_folder):
  img_path = with_mask_folder + filename
  img = Image.open(img_path)
  img = img.resize((128,128))
  img = img.convert('RGB')

  newImgPath = with_mask_resized_folder + filename
  img.save(newImgPath)

without_mask_folder = '/content/data/without_mask/'
without_mask_resized_folder = '/content/without_mask_resized/'
for filename in os.listdir(without_mask_folder):
  img_path = without_mask_folder + filename
  img = Image.open(img_path)
  img = img.resize((128,128))
  img = img.convert('RGB')

  newImgPath = without_mask_resized_folder + filename
  img.save(newImgPath)

img = mpimg.imread('/content/with_mask_resized/with_mask_10.jpg')
plt.imshow(img)

img = mpimg.imread('/content/with_mask_resized/with_mask_100.jpg')
plt.imshow(img)

img = mpimg.imread('/content/without_mask_resized/without_mask_10.jpg')
plt.imshow(img)

import cv2
import glob

# reading with_mask images
imdir = '/content/with_mask_resized/'
ext = ['png','jpg']

files = []
[files.extend(glob.glob(imdir + '*.'+ e)) for e in ext]

with_mask_images = np.asarray([cv2.imread(file) for file in files])

# reading without_mask images
imdir = '/content/without_mask_resized/'
ext = ['png','jpg']

files = []
[files.extend(glob.glob(imdir + '*.'+ e)) for e in ext]

without_mask_images = np.asarray([cv2.imread(file) for file in files])

print(with_mask_images)

print(without_mask_images)

print(with_mask_images.shape)
print(without_mask_images.shape)

combined_image = np.concatenate((with_mask_images, without_mask_images))

print(combined_image.shape)

print(combined_image)

# data and labels
X = combined_image
Y = np.asarray(labels)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

print(X.shape, X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)

print(X_train[0])

X_train_std = X_train/255
X_test_std = X_test/255

print(X_train_std)

import tensorflow as tf
import keras

model = keras.Sequential([
keras.layers.Flatten(input_shape=(128,128,3)),
keras.layers.Dense(70,activation='relu'),
keras.layers.Dense(70, activation='relu'),
keras.layers.Dense(2,activation='sigmoid')
                          ])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy']
              )

model.fit(X_train_std, Y_train, epochs=10)

score, acc = model.evaluate(X_test_std, Y_test)
print('Test data loss:', score)
print('Test data accuracy:', acc)

from google.colab.patches import cv2_imshow

input_image_path = input('Path of the image to be predicted :')
input_image = cv2.imread(input_image_path)

cv2_imshow(input_image)
input_image_resize = cv2.resize(input_image, (128,128))
input_image_resize = input_image_resize/255

image_reshape = np.reshape(input_image_resize,[1,128,128,3] )

input_prediction = model.predict(image_reshape)
print(input_prediction)

input_pred_label = np. argmax(input_prediction)
print(input_pred_label)

if input_pred_label == 1:
  print('The person is wearing mask')

else:
    print('The person is not wearing mask')

input_image_path = input('Path of the image to be predicted :')
input_image = cv2.imread(input_image_path)

cv2_imshow(input_image)
input_image_resize = cv2.resize(input_image, (128,128))
input_image_resize = input_image_resize/255

image_reshape = np.reshape(input_image_resize,[1,128,128,3] )

input_prediction = model.predict(image_reshape)
print(input_prediction)

input_pred_label = np. argmax(input_prediction)
print(input_pred_label)

if input_pred_label == 1:
  print('The person is wearing mask')

else:
    print('The person is not wearing mask')